"use client"
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Shopping online | Ecommerce",
//   description: "Generated by create next app",
// };
import dynamic from 'next/dynamic';

import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
//import "bootstrap/dist/js/bootstrap.bundle.js";
import { Providers } from "../redux/Providers";
// import Header from "@/components/Header";
const Header = dynamic(() => import('@/components/Header'), { ssr: false });
import TopMenu from "@/components/TopMenu";
import Footer from "@/components/Footer";
//import { BrowserRouter } from "react-router-dom";
import "./App.css";
//import { useEffect } from "react";

import { ToastContainer} from 'react-toastify';
import 'react-toastify/ReactToastify.min.css';
import { useEffect } from 'react';



export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min.js').then((Bootstrap) => {
      // Any Bootstrap initialization code can go here
    });
  }, []);

  return (<html lang="en">
    <head>
      <title>Your App Title</title>
    </head>
    <body>
   
      <Providers>
    
          <header>
          
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
    
            <Header />
            <TopMenu />
          </header>
          <main>
          <ToastContainer />
   
            {children}
           
            </main>
          <footer>
            <Footer />
          </footer>
      
      </Providers>

    </body>


  </html>

  );
}
